name: Release
'on':
  push:
    branches:
      - next
      - '*.x'
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npm test
  release:
    needs: [tests]
    name: release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Build Library
        run: npm run build
      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SR_NPM_TOKEN }}
          GIT_AUTHOR_NAME: 'Erik Blanca'
          GIT_AUTHOR_EMAIL: 'erik.bg7@gmail.com'
          GIT_COMMITTER_NAME: 'Erik Blanca'
          GIT_COMMITTER_EMAIL: 'erik.bg7@gmail.com'
